schema_version = "1.0.0"
id = "import_dxf_pro"
name = "DXF Import Pro (.dxf)"
version = "0.0.1"
tagline = "Import files in the Autocad DXF format (.dxf)"
maintainer = "Community"
type = "add-on"
tags = ["Import-Export"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]
website = "https://projects.blender.org/extensions/io_import_dxf"
copyright = [
    "2024 moshi",
]

dependencies = { python = ">=3.8" }

[requirements]
files = [
    "requirements.txt",
]

[install]
script = "install_dependencies.py"

auto_update = true

[permissions]
files = "Requires access to directory with .dxf files"
